package cn.lcs.generate.domain;

import javax.persistence.*;
import java.util.Date;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="go_config")
public class GoConfig {
	@Basic
	@Column(length=450)
	private String config;

	@Basic
	@Column(name="create_time", columnDefinition="TIMESTAMP", length=19)
	private Date createTime;

	@Basic
	@Column(length=400)
	private String description;

	@Id
	@Column(columnDefinition="INT")
	private int id;

	@Basic
	@Column(nullable=false, length=250)
	private String key;


	public GoConfig() {
	}

	public GoConfig(int id) {
		this.id = id;
	}

	public String getConfig() {
		return config;
	}

	public void setConfig(String config) {
		this.config = config;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}
}